--- 
- name: update web servers
  hosts: web

  tasks:
  - name: ensure apache is installed
    package:
      name: httpd
      state: present
      
   
  - name: ensure appache is started
    service:
      name: httpd
      state: started


...
