--- 
- name: update web servers
  hosts: web

  tasks:
  - name: ensure git is installed
    package:
      name: git
      state: present

  - name: ensure SELinux is permisive 
    selinux:
      policy: targeted
      state: permissive
 
  - name: ensure code  is updated
    git:
      repo: 'https://github.com/ravi2krishna/ecomm.git'
      dest: /var/www/html

...
