--- 
- name: update web servers
  hosts: web
  become: yes
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted


  tasks:
  - name: endure port is changed 
    copy: 
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart httpd

  - name: ensure SELinux is permisive 
    selinux:
      policy: targeted
      state: permissive

  - name: ensure data is update
    copy: 
      src: date.php
      dest: /var/www/html/data.php

  - name: PHP is installed
    package:
      name: php
      state: present  
    notify:
    - restart httpd


...
